### ISSUE TITLE
Request: Flushing Database and updating Images

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#10]
Chinzo - I'd like the ability to run a script or scripts that will remove images (all) or image list from database.    And Update the database to contain the tifs currently on the image server. 

Is that possible? - Noah

**Comment by ChinzoD** [comment]
I can create a python virtual environment for you. I will let you know once I create python3 environment.

**Comment by scinoah** [comment]
Does clicking on this link (image below) reload all tiffs (etc)? 

How does one remove all or specific images from Database (if they have been renamed)?

![Capture](https://user-images.githubusercontent.com/54286077/64284598-f43fb200-cf27-11e9-8a80-4a192a32449f.JPG)

**Comment by ChinzoD** [comment]
Yes, It will reload but if it is already registered in the database, it will skip.

**Comment by scinoah** [comment]
Chinzo If we need you to remove images, is it easier for us to just request that you empty out the database and we can reload them?  This will probably happen less and less.

**Comment by ChinzoD** [comment]
I can remove the data manually whenever you want to remove specific data or whole data. For the current small dataset, it is easier to delete all data and reload again by using AMIS load function. For the future, It is better and safe for specific data deletion.

**Comment by scinoah** [comment]
Sounds Good
