### ISSUE TITLE
Request Ability to run Python Scripts on Server

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#11]
Chinzo - Is it possible to run Sciimage Python scripts on server.  Would I need to load libraries locally or is there an approach (i.e. ananconda or pip) already in place. 

Thanks -Noah

**Comment by ChinzoD** [comment]
I have created a python3 environment.

**Comment by scinoah** [comment]
Able to run Python3.5, use pip to load libraries, log out, log back in and still access libraries (scikit-image)
