### ISSUE TITLE
Refreshing Search after switching from Cleared to Histological Dataset

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#14]
"When switching to cleared the organ dropdown menu does not update and shows all histology available organs. When switching from cleared after browsing the images the organ dropdown list does not show all available organs. Can we push an auto refresh to this dropdown when changing Sample type?"

**Comment by ChinzoD** [comment]
Could you please give me a diagram or list for filters as like below list? Users may don't notice previously selected filters updates automatically. It can cause confusion for users.

Gene dropdown updates =>  Organ
Organ updates => Experiment, Sample type
Experiment updates => nothing
Sample type updates > Experiment, Organ

**Comment by JGENGLISH** [comment]
Perhaps it would be easier to make empty dataset text grey, italic, none selectable, and put "(empty)" beside the text for categories for which there is no data? This might be easier to navigate than hiding the selection?

Gene updates => organ, experiment, sample
Organ updates => experiment, sample
Experiment => nothing
Sample type updates => Organ, Experiment

I believe there is a delay in the update occurring. Perhaps it processes this after loading all the image thumbnails or something?

**Comment by ChinzoD** [comment]
I think we need to keep selected filter somewhere and that is changeable from other filters. From the below list, it updates your previously selected filters. For example: step => user selects "gene", step 2: user selects "sample type" but it updates your previously selected gene. So we need to lock the selected filters.

Gene updates => organ, experiment, sample
Organ updates => experiment, sample
Experiment => nothing
Sample type updates => Organ, Experiment

We need to keep track of previously selected filters that cannot be able to changeable unless the user deletes the filter selection. Please see the below example. We can use a similar filter like carmax.com. 

![Screenshot from 2019-09-10 10-25-25](https://user-images.githubusercontent.com/22141182/64636245-2765c380-d3b6-11e9-9d8f-b44d19bce580.png)

**Comment by JGENGLISH** [comment]
OK. But we aren't going to use this kind of approach, right? Because unlike a list to shop from the user should only be delivered one selected dataset at a time.

The primary issue is that when changing options the organ list does not update when changing choices in the drop downs. It updates once we begin browsing the images, could we just queue in a page refresh when they change the drop down options?

**Comment by ChinzoD** [comment]
Completed

**Comment by JGENGLISH** [comment]
This is working but there are two changes that need to be made:

Make nothing update experiment and have "Experiment" default to Ai9 as we have no other data type for this at the moment and it results in excessive clicking by the user.

Sample type needs to always display histology and clearing, as we discussed, so that users can switch to cleared and see what datasets are available to browse at any time.

If necessary we can put "sample type" at the top above Gene/Organ etc. to indicate to the user that this is the primary selection for browsing. Default to choosing Histological for this and the user can switch clearing.

**Comment by JGENGLISH** [comment]
Also let's default to content-containing datasets rather than "select" -- or if we are using the "select" as a blank display no data until all choice fields have a selection. The website is currently displaying random data if a field is not chosen.

**Comment by ChinzoD** [comment]
Currently, it is not displaying anything if all of the fields selected "select" option. If you select a different choice other than "select", It will display data filtered by your choice but not displaying random data. If you want to change default selection to first data(other than "select") from the dropdown list, please let me know.

**Comment by JGENGLISH** [comment]
![example](https://user-images.githubusercontent.com/54285860/64982913-4c15db80-d88d-11e9-8185-8f8b96de0982.png)

Got it. Sorry, here is what I mean (see screen shot). Choosing "GPR68" loads 268 images and the buttons for every available mouse dataset (cleared and histology).

Let's have the user select Sample Type (move to top, master selector)

Have "sample type" dictate what gene/organs the user can choose from. If they select an organ have that update the gene, if they select a gene, have that update the organ.

For default selections:
sample type>histology
experiment>Ai9

Also if the user comes in from the homepage by clicking the representative image link "Click here to see full dataset" the list fills for Gene and Organ but not for sample type and experiment. It should select in to those values as well.

Let me know if that's unclear, can chat on phone too!

**Comment by ChinzoD** [comment]
Updated. Please let me know if you have any comments.

**Comment by JGENGLISH** [comment]
Sample Type needs to always be able to toggle between histology and cleared and I think we should move it to the top of the list of categories on the webpage.

Defaults working well now.

**Comment by ChinzoD** [comment]
Is it ok to display not found msg when there is no data related to the selected Sample type? 
Another solution to see both sample types is adding a new button that clears the current selection of all dropdowns. It means that you can see all the possible values for all dropdowns.

**Comment by JGENGLISH** [comment]
If the toggle between cleared and histology can we default clear all other
selections?

**Comment by ChinzoD** [comment]
Does "clear all other selections" mean that changing other selections to "select"?

**Comment by JGENGLISH** [comment]
Yes. Or better, cause it to default to the first available dataset.

**Comment by ChinzoD** [comment]
Got you. Could you please change below update rules again?

Gene updates => organ, experiment, sample
Organ updates => experiment, sample
Experiment => nothing
Sample type updates => Organ, Experiment

**Comment by ChinzoD** [comment]
Could you please check the following update rules? If it looks good, I am gonna change dropdowns

1.Sample type updates => Gene, Organ, Experiment  /Change other dropdowns to "select" option/
2.Gene updates => organ, experiment
3.Organ updates => experiment
4.Experiment => nothing

**Comment by scinoah** [comment]
Hi Chinzo - That looks good to me - the Experiment categories may expand from one (n=1) and change at that point. Thanks -Noah

________________________________

**Comment by scinoah** [comment]
Hi Chinzo - Justin had another point he wanted to raise about #3 (Organ Updates) option. He'll send out an email. -Noah

________________________________

**Comment by scinoah** [comment]
Hey there,

Sorry about this. I didn't loop back for your previous request Chinzo. Can we do the following:

1.Sample type updates => Gene, Organ, Experiment /Change other dropdowns to "select" option/
2.Gene updates => organ, experiment
3.Organ updates => GENE, experiment
4.Experiment => nothing

with experiment defaulted at all times to Ai9.

It should be possible for a user to choose histology or cleared in #1 and then select either an option from #2 or #3 to innumerate the other list. Fine if a choice in #2 or #3 locks the filtering after. We can put a "clear selection" button as you mentioned to facilitate?

Justin G. English, PhD
Laboratory of Bryan Roth, MD PhD
UNC Chapel Hill Department of Pharmacology

________________________________________

**Comment by ChinzoD** [comment]
Fixed. Please check it

**Comment by JGENGLISH** [comment]
Great. When switching Sample Type let's have the selections default to the first choice in each drop down (same as when coming to the image browser for the first time). Right now it tries to load every image in histological or cleared datasets when toggling between them.

**Comment by JGENGLISH** [comment]
Also let's default experiment to Ai9 for every selection unless the users changes it otherwise.

**Comment by JGENGLISH** [comment]
Clearing all filters and then loading a sample type still causes all the data on the server to load to the browser at once. Probably should restrict loading of any files until sample type, gene, and organ have been chosen. No one will want to see any data displays before that time as it is not organized or annotated.

**Comment by scinoah** [comment]
So that means - as it is now one would make 3 selections before any updating the website's screen. - Noah

1) Sample Type --> Histological   (No Update)
2) Gene --> GPCR85                      (No Update)
3) Organ --> brain                          (Now an update)
4) Experiment --> Ai9 (by default)

________________________________

**Comment by ChinzoD** [comment]
Hi Justin & Noah,

I have a couple of questions to clarify your request.

1. What does no update mean? Is it for no updating and filtering other dropdowns(Answer 1) or no updating the 6 images (Answer 2)?
2. (If your answer is 1): If I change Sample type and then there is no update it means that you can see all gene, even if there are no data related to that gene.
3. (If your answer is 2): If I change the Sample type it updates and filters the other dropdowns but not the 6 images. How do users know they need to choose at least 3 selections?

**Comment by JGENGLISH** [comment]
Answer 2

We could put an image in the top left corner of the 6 image viewer that says something like
 "please select a sample, gene, and organ type"

this could be the only thing that populates the table until all 3 drop downs have a selection.

In it's current state if a user selects "cleared" as the sample type and nothing else the server attempts to load thousands and thousands of images without context.

**Comment by ChinzoD** [comment]
Updated. Please check.

**Comment by JGENGLISH** [comment]
Filtering is now failing. If I select "Cleared" as the Sample Type it allows me to choose GPR85>bladder for which there is no data available.

Switching to histological works and clears the other selections allowing me to re-select. Let's remove "select" from experiment type and default to Ai9 and we can add others later -- because currently leaving this unselected still displays data and this may confuse users.

**Comment by ChinzoD** [comment]
Fixed. Please check

**Comment by scinoah** [comment]
Looks great - but needs some type of instruction for the user how to proceed.

**Comment by ChinzoD** [comment]
I have changed the unselected(sample type, gene, organ) dropdown's color to red. Please test it and if you think it is not enough for instruction, I will add some text under the dropdown fields.

**Comment by JGENGLISH** [comment]
I believe we were going to add text in the image display fiels when no
images were being displayed instructing user to make a choice. Text beside
the dropdown may also work?

**Comment by scinoah** [comment]
Hi Chinzo -

I like that (red font) a lot - a simple way of guiding visitors.

We might have a small to modest addition to the web site soon - and after that, we should show some scientists/guinea pigs
our web site and see what types of issues they experience.

-Noah

________________________________

**Comment by ChinzoD** [comment]
I have added the text instruction under the "not found" image.

**Comment by JGENGLISH** [comment]
Looks great, working well.
