### ISSUE TITLE
Decrease Rendering time for Zoomed jpegs(?) 

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#18]
"Is it possible to make rendering of double-clicked images (full size) faster? Is the bottle neck for rendering user side or server side?"

Is this hardware, software, it has something to do with local computer/internet too.

**Comment by ChinzoD** [comment]
Image size is the bottle neck

**Comment by jir322** [comment]
John says:  This is a topic for our next teleconference.  No action for now.
