### ISSUE TITLE
Renamed jpgs and pngs aren't repopulating

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#24]
Renames certain files by removing ".tif" string from jpg and png files (see attached file). 

For example See URL = http://amis.docking.org/img_browser?gene=TAS2R4&organ=brain&experiment=Ai9&instrument=Histological&wavelength=tdTomato&pos_mouse_number=2408&neg_mouse_number=2410&selected_slice=1

[rename.txt](https://github.com/docking-org/AMIS/files/3605924/rename.txt)

**Comment by scinoah** [comment]
Chinzo -  I see it in the terminal.

[cid:0fa7bd4f-da69-4171-a8e0-767c77280160]

I downloaded a list of images in directory 2048 and it appears that all the expected image files are there.

Thanks -Noah

2408/TAS2R4_Ai9_1_1_2408_f_p30_reporter-gene-cross_brain_955_c_1_00001_10x_Olympus_tdTomato_d780d2692a50d4c96c78c49c4c7ddb4e.png




________________________________

**Comment by ChinzoD** [comment]
Did you delete tif data recently? I deleted all slice from the database and reloaded again. Now it looks good.
