### ISSUE TITLE
Can't seem to get Python3 to activate in hidden directory 

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#26]
(python3_env) -sh-4.1$ source /home/justin/upload/python3_env_hidden/bin/activate
(python3_env) -sh-4.1$ python -V
Python 2.6.6
(python3_env) -sh-4.1$

**Comment by ChinzoD** [comment]
Could you please check it again? Please install the packages again.

**Comment by scinoah** [comment]
Able to activate and reinstalled python packages.

However getting the DOS Attack warning after running my python program (Rotate.py)

(python3_env_hidden) -sh-4.1$ python Rotate.py
./2445/GPR68_Ai9_1_1_2445_f_p30_reporter-gene-cross_brain_955_c_2_00018_10x_Olympus_tdTomato_d410922d1d99cce929fb0128049f6636.tif
./2445/GPR68_Ai9_1_1_2445_f_p30_reporter-gene-cross_brain_955_c_2_00018_10x_Olympus_tdTomato_d410922d1d99cce929fb0128049f6636_RI.jpg
/mnt/nfs/ex9/idg-images/python3_env_hidden/lib/python3.6/site-packages/PIL/Image.py:2735: DecompressionBombWarning: Image size (173067180 pixels) exce                                                                      eds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning,


________________________________

**Comment by ChinzoD** [comment]
Looks like it exceeds the file size limit. I googled it and this link has instruction to solve it. https://github.com/zimeon/iiif/issues/11

**Comment by scinoah** [comment]
Oh - I assumed it was a local/server issue. Thanks for link - Noah

________________________________
