### ISSUE TITLE
Update upper 6 images first, before bottom slice panel is updated

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#29]

**Comment by ChinzoD** [comment]
Fixed. Please check

**Comment by JGENGLISH** [comment]
Needs adjustment.

It quickly updated the "tdTomato" image but the "tdTomato RI" and "DAPI" images will not update until the thumbnails at the bottom have loaded.

This is most obvious when viewing cleared datasets, as the thumbnail set is very large.

**Comment by ChinzoD** [comment]
Not solved the issue but might be a little bit improved. We need to find out the caching solution for the images.

**Comment by JGENGLISH** [comment]
Ok. No problem, will check it out.

**Comment by ChinzoD** [comment]
Fixed by resizing thumbnail images from png to .webp. I also reduced quality by 50%. Now it loads much faster
