### ISSUE TITLE
Adjust Negative and Positive Controls for Genotype=2 

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#41]
For the initial images (GPR85,GPR68)  when  Genotype = 0  Negative Control and Genotype = 1 Positive Control 

The new sets of images are Genotype = 2,  (4th category --> HCAR_Ai9_1_2)
So in this case the the Negative Control Images have "reporter-gene-cross-VEH" and the Positive Controls have "reporter-gene-cross-TAM" in their names (see 2 examples below)
 
Negative Control    
HCAR1_Ai9_1_2_425001_f_p56_reporter-gene-cross-VEH_tongue_1723_nd_1_00001_10X_Olympus_tdTomato_e7d7cf1a1b39bf7a1f41ec8b54186506.png

Positive Control 
HCAR1_Ai9_1_2_426001_f_p56_reporter-gene-cross-TAM_tongue_1723_nd_01_00001_10X_Olympus_tdTomato_045ce5fdbfa76db84b9bc76855489a62.png

**Comment by ChinzoD** [comment]
Fixed. Please test
