### ISSUE TITLE
Question about Image sequences

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#42]
If an image is removed from the website (due to poor quality) , does the sequence automatically adapt? 

That is 1-2-3-4-5,  remove images 3 and 4 will 1-2-5 be displayed? For Example that is _00001_, _00002_, _00003_, etc

Example: 
ADGRB2_Ai9_1_2_326002_m_p56_reporter-gene-cross-TAM_eyes_19_nd_1_00001_10X_Olympus_DAPI_70b939cdc62a8f1632d8caa43c7a9a2d

**Comment by ChinzoD** [comment]
We also need to delete those from the database also. Otherwise it will show the data without image.

**Comment by scinoah** [comment]
So for example, for mouse# 426002, bladder,  I physically removed the images for slice # 00004 (see file list below from website directory=426002) .

The website (http://amis.docking.org/img_browser?gene=ADGRB2&organ=bladder&experiment=Ai9&instrument=Histological&wavelength=tdTomato&pos_mouse_number=426002&selected_slice=4)
shows a image "holder".  As the Images are not there -- is there a way for me to remove the image names from the database too?

Thanks - Noah

[cid:3b2b1e36-074a-4afd-8e52-d5eac93338fd]

________________________________
