### ISSUE TITLE
Website Modfication Requests

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#43]
![Changes](https://user-images.githubusercontent.com/54286077/125826885-c49d7243-040b-420a-a291-b8f50e790445.jpg)
![Current](https://user-images.githubusercontent.com/54286077/125826886-395bdb20-2da7-4e1f-997d-233e4b82f813.jpg)

- 
See Image or contact me for Clarifications: 

•	Adjust png Size at bottom,  rescale images to 100%, 
•	Move Buttons etc.  
        Move TdTomato, tdTomato-RI,Dapi, Invert color, Change background color, Download Tiff file, and Sharable URL
        To bottom left and add some type of frame around them 
•	Move Navigation Buttons
        From Middle to Bottom Center 
•	Add Controls in font
	Add text for “positive controls” (top) and “negative controls” (bottom)
•	Hide MD5 value tag from Web Access but not from Me
        Add an Editor or Secret Mode?
•	Move LUT Bar
        Move from Right Side to adjacent to tdTomato RI image

**Comment by ChinzoD** [comment]
Completed

**Comment by scinoah** [comment]
Looks good to me!  Thanks - Noah

________________________________
