### ISSUE TITLE
Removed Organ Categories remain without any images

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#45]
I replaced some images this morning, MTNRIA "Jej", "Liver" and "Colon" with renamed images to "jej", "liver", and "colon". The
misnamed images are no longer there, but the categories seem to be there 

For Example: 
http://amis.docking.org/img_browser?gene=MTNRIA&organ=Jej&instrument=Histological&wavelength=tdTomato&pos_mouse_number=326003&selected_slice=1

**Comment by ChinzoD** [comment]
I deleted it from the database. When you run loadimages script, it stores in the database but it will not delete old one. We can only delete those by manually
