### ISSUE TITLE
Remove + and - characters from label 

### ISSUE THREAD

**Issue by scinoah** [docking-org/AMIS#51]
The + and - characters are only correct for genotypes 1 and 0 (positive and negative), as we move to different
schemes (such as genotype 2 where positive is TRAM-treated and negative is VEH-treated), the + and - will confuse molecular geneticists.  So it is better to just have mice categorized under Positive  or Negative Controls. 

For example in : http://amis.docking.org/img_browser?gene=GPR85&organ=brain&experiment=Ai9&instrument=Histological&wavelength=tdTomato&pos_mouse_number=2505&neg_mouse_number=1537&selected_slice=14

"+ ♀ p30 2505"   should now be "♀ p30 2505"

Hope that makes sense - Noah

**Comment by ChinzoD** [comment]
Solved
